#!/usr/bin/env bash
# configures a server to listening on port 80.

#remove the default nginx configuration
rm /etc/nginx/sites-enabled/default

#configure nginx to listen on port 80 for all active ipv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
service nginx restart
